#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
sync_articles.py —— 把 Obsidian 里的公众号文章，同步成网站的静态文章页

它做四件事：
  1. 读取 Obsidian 文章源文件夹里的 .md（默认只收 status: 已发布 的）
  2. 转成网站用的 HTML（自动过滤「内部信息」、处理插图）
  3. 把插图复制进 web/assets/img/articles/<文章短名>/
  4. 重新生成文章列表页 web/articles/index.html 和首页用的数据文件

用法（在项目根目录执行）：
    双击「同步文章.command」              # 最省事
    python3 tools/sync_articles.py        # 同步全部「已发布」文章
    python3 tools/sync_articles.py 吃饭 跑步   # 只同步文件名含这些词的文章（试水用）

网站本身零依赖：本脚本只在「同步」这一步用到，访客看站不需要它。
"""

import datetime
import hashlib
import html as html_lib
import os
import re
import shutil
import struct
import subprocess
import sys
import urllib.request
from urllib.parse import quote

# ============================================================
# 配置（要改路径就改这里）
# ============================================================

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Obsidian 里放文章的总目录 + 只同步哪个子文件夹
VAULT_ARTICLES_DIR = "/Users/Admin/Knowledge/ChesterObsidian/个人管理/文章输出"
SOURCE_SUBDIR = "03_已发布"

# 只同步 frontmatter 里 status 等于这个值的文章
WANT_STATUS = "已发布"

# 网站目录
WEB_DIR = os.path.join(PROJECT_ROOT, "web")
ARTICLES_DIR = os.path.join(WEB_DIR, "articles")
IMG_DIR = os.path.join(WEB_DIR, "assets", "img", "articles")
DATA_JS = os.path.join(WEB_DIR, "assets", "js", "articles-data.js")

# 站点信息（文章页会用到）
SITE_NAME = "i雅俗共赏 · Chester"
SITE_TAGLINE = "我想成为更好的自己。"
SITE_BRAND = "i雅俗共赏"
GENERATED_MARK = "<!-- generated by tools/sync_articles.py -->"

WARNINGS = []


def warn(msg):
    WARNINGS.append(msg)


# ============================================================
# 1. 读文件 / 解析 frontmatter
# ============================================================

def read_text(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return f.read().lstrip("\ufeff")


def split_frontmatter(text):
    """拆出 YAML frontmatter（只支持本项目用到的简单写法）和正文。"""
    m = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n?", text, re.S)
    if not m:
        return {}, text
    data = {}
    key = None
    for line in m.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        item = re.match(r"^\s+-\s+(.*)$", line)
        if item and key:
            if not isinstance(data.get(key), list):
                data[key] = []
            data[key].append(unquote_scalar(item.group(1)))
            continue
        kv = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", line)
        if kv:
            key = kv.group(1)
            value = kv.group(2).strip()
            data[key] = [] if value == "" else unquote_scalar(value)
    return data, text[m.end():]


def unquote_scalar(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def first_heading(text):
    for line in text.splitlines():
        m = re.match(r"^#\s+(.*)$", line.strip())
        if m:
            return m.group(1).strip()
    return None


def plain_text(md):
    """把一行 markdown 变成纯文字（用于生成摘要）。"""
    s = re.sub(r"!\[\[[^\]]*\]\]", "", md)
    s = re.sub(r"!\[[^\]]*\]\([^)]*\)", "", s)
    s = re.sub(r"\[\[([^\[\]|]+)\|([^\[\]]+)\]\]", r"\2", s)
    s = re.sub(r"\[\[([^\[\]]+)\]\]", r"\1", s)
    s = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", s)
    s = re.sub(r"[*`_>#]", "", s)
    return s.strip()


# ============================================================
# 2. 图片：读尺寸 + 复制进站
# ============================================================

def image_size(path):
    """纯 Python 读 PNG / JPEG / GIF 的宽高，失败返回 (None, None)。"""
    try:
        with open(path, "rb") as f:
            head = f.read(32)
            if head[:8] == b"\x89PNG\r\n\x1a\n":
                w, h = struct.unpack(">II", head[16:24])
                return w, h
            if head[:6] in (b"GIF87a", b"GIF89a"):
                w, h = struct.unpack("<HH", head[6:10])
                return w, h
            if head[:2] == b"\xff\xd8":
                f.seek(2)
                while True:
                    b = f.read(1)
                    if not b:
                        return None, None
                    if b != b"\xff":
                        continue
                    marker = f.read(1)
                    while marker == b"\xff":
                        marker = f.read(1)
                    if not marker:
                        return None, None
                    code = marker[0]
                    if code in (0xD8, 0x01) or 0xD0 <= code <= 0xD7:
                        continue
                    seg = f.read(2)
                    if len(seg) < 2:
                        return None, None
                    length = struct.unpack(">H", seg)[0]
                    if 0xC0 <= code <= 0xCF and code not in (0xC4, 0xC8, 0xCC):
                        info = f.read(5)
                        if len(info) < 5:
                            return None, None
                        h, w = struct.unpack(">HH", info[1:5])
                        return w, h
                    f.seek(length - 2, 1)
    except Exception:
        return None, None
    return None, None


def sniff_ext(path):
    """看文件头判断图片格式，返回扩展名。"""
    try:
        with open(path, "rb") as f:
            head = f.read(12)
    except OSError:
        return ".jpg"
    if head[:8] == b"\x89PNG\r\n\x1a\n":
        return ".png"
    if head[:2] == b"\xff\xd8":
        return ".jpg"
    if head[:6] in (b"GIF87a", b"GIF89a"):
        return ".gif"
    if head[:4] == b"RIFF" and head[8:12] == b"WEBP":
        return ".webp"
    return ".jpg"


def png_has_alpha(path):
    try:
        with open(path, "rb") as f:
            head = f.read(26)
    except OSError:
        return False
    return head[:8] == b"\x89PNG\r\n\x1a\n" and head[25] in (4, 6)


def sips(args):
    """调用 macOS 自带的 sips；失败就安静放过。"""
    try:
        subprocess.run(
            ["sips"] + args,
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return True
    except Exception:
        return False


def optimize_image(path):
    """
    把图片压到站内可接受的大小（长边 ≤ 2000px、尽量 ≤ 500KB）。
    只动网站里的副本，不碰 Obsidian 原图。返回最终文件路径（可能换了扩展名）。
    """
    if not shutil.which("sips"):
        return path
    w, h = image_size(path)
    if w and h and max(w, h) > 2000:
        sips(["-Z", "2000", path])
    if os.path.getsize(path) <= 500 * 1024:
        return path
    if png_has_alpha(path):
        return path                     # 带透明的图不转 JPEG，只缩边
    jpg = os.path.splitext(path)[0] + ".jpg"
    if os.path.abspath(jpg) == os.path.abspath(path):
        # 已经是 JPEG：重压到临时文件，更小才替换（直接输出同名会把原图删掉）
        tmp = path + ".opt.jpg"
        ok = sips(["-s", "format", "jpeg", "-s", "formatOptions", "80",
                   "-Z", "2000", path, "--out", tmp])
        if ok and os.path.isfile(tmp) and os.path.getsize(tmp) < os.path.getsize(path):
            os.replace(tmp, path)
        elif os.path.isfile(tmp):
            os.remove(tmp)
        return path
    if sips(["-s", "format", "jpeg", "-s", "formatOptions", "80", "-Z", "2000", path, "--out", jpg]):
        if os.path.isfile(jpg) and os.path.getsize(jpg) < os.path.getsize(path):
            os.remove(path)
            return jpg
        if os.path.isfile(jpg):
            os.remove(jpg)
    return path


def site_image_url(slug, filename):
    return "../assets/img/articles/%s/%s" % (slug, quote(filename))


def copy_image(src, slug):
    """把本地图片复制进 web/assets/img/articles/<slug>/，返回站内相对路径。"""
    name = os.path.basename(src)
    dest_dir = os.path.join(IMG_DIR, slug)
    if not os.path.isdir(dest_dir):
        os.makedirs(dest_dir)
    dest = os.path.join(dest_dir, name)
    if (not os.path.exists(dest)) or os.path.getmtime(src) > os.path.getmtime(dest):
        shutil.copy2(src, dest)
        dest = optimize_image(dest)
    warn_if_big(dest)
    return site_image_url(slug, os.path.basename(dest))


def download_image(url, slug):
    """把外链图片（如公众号的 mmbiz）下载进站，避免外站失效或防盗链。"""
    clean = html_lib.unescape(url).split("#")[0]
    digest = hashlib.md5(clean.encode("utf-8")).hexdigest()[:10]
    dest_dir = os.path.join(IMG_DIR, slug)
    if not os.path.isdir(dest_dir):
        os.makedirs(dest_dir)
    for name in sorted(os.listdir(dest_dir)):
        if name.startswith("web-" + digest + "."):
            cached = optimize_image(os.path.join(dest_dir, name))   # 首次可能没压成功，这里补压
            warn_if_big(cached)
            return site_image_url(slug, os.path.basename(cached))
    tmp = os.path.join(dest_dir, "web-%s.part" % digest)
    req = urllib.request.Request(
        clean,
        headers={
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
            "Referer": "https://mp.weixin.qq.com/",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=20) as resp, open(tmp, "wb") as f:
            shutil.copyfileobj(resp, f)
    except Exception:
        if os.path.exists(tmp):
            os.remove(tmp)
        warn("外链图片下载失败，已保留原链接：%s" % clean[:80])
        return html_lib.escape(url, quote=True)
    dest = os.path.join(dest_dir, "web-%s%s" % (digest, sniff_ext(tmp)))
    os.rename(tmp, dest)
    dest = optimize_image(dest)
    warn_if_big(dest)
    return site_image_url(slug, os.path.basename(dest))


def warn_if_big(path):
    if os.path.getsize(path) > 500 * 1024:
        warn(
            "图片仍偏大（%d KB）：%s —— 建议在 Obsidian 里换一张更小的图"
            % (os.path.getsize(path) // 1024, os.path.relpath(path, PROJECT_ROOT))
        )


# ============================================================
# 3. Markdown -> HTML
# ============================================================

NOISE_TEXT = re.compile(
    r"^\s*(暂无评论|点赞|在看|分享|收藏|写留言|预览时标签不可点|"
    r"点击上方.{0,10}关注|扫码关注|长按识别|阅读原文)\s*$"
)
META_LINE = re.compile(
    r"^\s*\*\*\s*(题图标题|题图说明|题图|封面|创作者|作者|AI\s*算法提供|算法提供|Prompt|图片来源)\s*\*\*\s*[:：]?"
)
META_DATE = re.compile(r"^\s*[（(]?\s*(原文日期|首发日期|发布日期|发布时间|文章日期)\s*[:：]")
WIKI_IMG = re.compile(r"!\[\[([^\[\]]+?)\]\]")
MD_IMG = re.compile(r"!\[([^\]]*)\]\(([^)\s]+)\)")
ONLY_IMG = re.compile(r"^\s*!\[[^\]]*\]\(([^)\s]+)\)\s*$")
WIKI_LINK = re.compile(r"\[\[([^\[\]]+?)\]\]")
FENCE = re.compile(r"^\s*(```|~~~)")


def norm_escape(text, quote=True):
    """先解掉源文里已有的 HTML 实体，再统一转义，避免出现 &amp;amp; 这种双重转义。"""
    return html_lib.escape(html_lib.unescape(text), quote=quote)


def convert_body(raw, md_dir, slug, title):
    """把正文 markdown 转成 HTML 片段，返回 (html, first_image_url, summary_candidates)。"""
    state = {"first_img": None, "paras": []}

    def resolve_image(target):
        target = target.strip()
        if target.startswith("../assets/"):
            return target            # 已经解析过的站内路径（如引用块二次处理）
        if re.match(r"^(https?:)?//", target):
            return download_image(target, slug)
        if target.startswith("data:"):
            return None
        candidates = [
            os.path.join(md_dir, target),
            os.path.join(VAULT_ARTICLES_DIR, target),
            os.path.join(os.path.dirname(VAULT_ARTICLES_DIR), target),
        ]
        src = next((c for c in candidates if os.path.isfile(c)), None)
        if src is None:
            warn("找不到插图：%s（文章：%s）" % (target, title))
            return None
        url = copy_image(src, slug)
        if state["first_img"] is None:
            state["first_img"] = url
        return url

    def repl_wiki_img(m):
        target = m.group(1).split("|")[0].strip()
        url = resolve_image(target)
        return "" if url is None else "![](%s)" % url

    def repl_md_img(m):
        alt, src = m.group(1), m.group(2)
        if src.startswith("data:"):
            return ""            # 公众号导出带的 1px 占位图，丢掉
        url = resolve_image(src)
        if url is None:
            return "" if not alt else alt
        return "![%s](%s)" % (alt, url)

    def inline(text):
        stash = []

        def keep(fragment):
            stash.append(fragment)
            return "\x00%d\x00" % (len(stash) - 1)

        text = WIKI_LINK.sub(
            lambda m: keep(norm_escape(wiki_label(m.group(1)), quote=False)), text
        )
        text = MD_IMG.sub(lambda m: keep(img_tag(m.group(2), m.group(1))), text)
        text = re.sub(
            r"\[([^\]]+)\]\(([^)\s]+)\)",
            lambda m: keep(
                '<a href="%s" target="_blank" rel="noopener">%s</a>'
                % (norm_escape(m.group(2)), norm_escape(m.group(1), quote=False))
            ),
            text,
        )
        s = html_lib.escape(text, quote=False)
        s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
        s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
        s = re.sub(r"(?<!\*)\*([^*\n]+)\*(?!\*)", r"<em>\1</em>", s)
        s = re.sub(r"(?<![\w_])_([^_\n]+)_(?![\w_])", r"<em>\1</em>", s)
        for index, fragment in enumerate(stash):
            s = s.replace("\x00%d\x00" % index, fragment)
        return s

    def img_tag(url, alt):
        alt = alt.strip() or title
        extra = ""
        local = os.path.normpath(os.path.join(ARTICLES_DIR, url))
        if os.path.isfile(local):
            w, h = image_size(local)
            if w and h:
                extra = ' width="%d" height="%d"' % (w, h)
        return '<img src="%s" alt="%s"%s loading="lazy">' % (
            norm_escape(url), norm_escape(alt), extra)

    lines = raw.splitlines()
    blocks = []
    paragraph = []

    def flush_paragraph():
        if not paragraph:
            return
        text = "<br>".join(paragraph)
        blocks.append("<p>%s</p>" % inline(text))
        plain = plain_text(" ".join(paragraph))
        if len(plain) >= 12 and not re.match(r"^(大家好|我是\s*Chester|背景[:：])", plain):
            state["paras"].append(plain)
        paragraph[:] = []

    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # 公众号导出噪声
        if NOISE_TEXT.match(stripped):
            flush_paragraph()
            i += 1
            continue
        if META_LINE.match(stripped) or META_DATE.match(stripped):
            flush_paragraph()
            i += 1
            continue
        if "data:image/svg+xml" in line:
            flush_paragraph()
            i += 1
            continue

        # 「版本管理」这类 callout：整块丢掉
        if re.match(r"^\s*>\s*\[!", line) and re.search(r"(版本管理|内部|草稿|待办)", line):
            flush_paragraph()
            while i < len(lines) and lines[i].lstrip().startswith(">"):
                i += 1
            continue

        # 图片/链接预处理
        line = WIKI_IMG.sub(repl_wiki_img, line)
        line = MD_IMG.sub(repl_md_img, line)
        stripped = line.strip()

        if not stripped:
            flush_paragraph()
            i += 1
            continue

        # 整行只有一张图 → 单独成块，不跟正文挤在一段里
        only_img = ONLY_IMG.match(line)
        if only_img:
            flush_paragraph()
            blocks.append("<figure>%s</figure>" % img_tag(only_img.group(1), ""))
            i += 1
            continue

        # 代码块
        if FENCE.match(line):
            flush_paragraph()
            fence = FENCE.match(line).group(1)
            i += 1
            code = []
            while i < len(lines) and not lines[i].strip().startswith(fence):
                code.append(lines[i])
                i += 1
            i += 1
            blocks.append(
                "<pre><code>%s</code></pre>" % html_lib.escape("\n".join(code), quote=False)
            )
            continue

        # 分隔线（连续多条只留一条）
        if re.match(r"^\s*(-{3,}|\*{3,}|_{3,})\s*$", line):
            flush_paragraph()
            if blocks and blocks[-1] != "<hr>":
                blocks.append("<hr>")
            i += 1
            continue

        # 标题
        heading = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if heading:
            flush_paragraph()
            level = len(heading.group(1))
            text = heading.group(2).strip()
            if level == 1 and plain_text(text) == plain_text(title):
                i += 1          # 页面顶部已显示标题，正文里不重复
                continue
            if level == 1:
                i += 1
                continue
            blocks.append("<h%d>%s</h%d>" % (level, inline(text), level))
            i += 1
            continue

        # 引用
        if stripped.startswith(">"):
            flush_paragraph()
            quote = []
            while i < len(lines) and lines[i].lstrip().startswith(">"):
                quote.append(re.sub(r"^\s*>\s?", "", lines[i]))
                i += 1
            inner = convert_body("\n".join(quote), md_dir, slug, title)[0]
            blocks.append("<blockquote>%s</blockquote>" % inner.replace("<p>", "").replace("</p>", ""))
            continue

        # 列表
        if re.match(r"^\s*[-*+]\s+", line):
            flush_paragraph()
            items = []
            while i < len(lines):
                m = re.match(r"^\s*[-*+]\s+(.*)$", lines[i])
                if not m:
                    break
                items.append("<li>%s</li>" % inline(m.group(1)))
                i += 1
            blocks.append("<ul>%s</ul>" % "".join(items))
            continue

        if re.match(r"^\s*\d+[.)]\s+", line):
            flush_paragraph()
            items = []
            while i < len(lines):
                m = re.match(r"^\s*\d+[.)]\s+(.*)$", lines[i])
                if not m:
                    break
                items.append("<li>%s</li>" % inline(m.group(1)))
                i += 1
            blocks.append("<ol>%s</ol>" % "".join(items))
            continue

        paragraph.append(line.strip())
        i += 1

    flush_paragraph()
    return "\n".join(blocks), state["first_img"], state["paras"]


def wiki_label(target):
    if "|" in target:
        return target.split("|", 1)[1].strip()
    return target.split("/")[-1].strip()


# ============================================================
# 4. 页面模板
# ============================================================

HEAD_TPL = """<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="stylesheet" href="{css}">
</head>
<body>
"""

TOPBAR_TPL = """<nav class="ps-topbar" aria-label="主导航">
  <div class="ps-topbar__inner">
    <a class="ps-topbar__brand" href="{home}">{brand}</a>
    <div class="ps-topbar__links">
      <a href="{home}"{cur_home}>首页</a>
      <a href="{about}">关于我</a>
      <a href="{works}"{cur_works}>作品</a>
      <a href="{articles}"{cur_articles}>文章</a>
    </div>
  </div>
</nav>
"""

FOOT_TPL = """<footer class="ps-footer">
  <div class="ps-footer__inner">
    <p class="ps-footer__line1">最后，祝你成为超人。</p>
    <p class="ps-footer__line2">在我的语境中有两层意思</p>
    <p class="ps-footer__line3">在生活中游刃有余的人</p>
    <p class="ps-footer__line4">「人应该是被超越的某种东西。」—— 尼采</p>
    <p class="ps-footer__meta">俗到极致即为雅，雅得过头便是俗——是谓i雅俗共赏。<span class="ps-footer__meta-sep">／</span>© 2026 张诚</p>
  </div>
</footer>
<script src="{js}"></script>
</body>
</html>
"""

ARTICLE_TPL = """<article class="ps-post">
  <header class="ps-post__head">
    <h1 class="ps-post__title">{title}</h1>
    <p class="ps-post__meta">{date}</p>
  </header>
  <div class="ps-post__body">
{body}
  </div>
</article>
"""

LIST_TPL = """<main class="ps-list">
  <header class="ps-list__head">
    <h1 class="ps-list__title">文章</h1>
    <p class="ps-list__sub">{count} 篇 · 同步自 Obsidian</p>
  </header>
  <ul class="ps-list__items">
{items}
  </ul>
</main>
"""

LIST_ITEM_TPL = """    <li class="ps-item">
      <a class="ps-item__link" href="{url}">
        {thumb}
        <div class="ps-item__text">
          <time class="ps-item__date">{date}</time>
          <h2 class="ps-item__title">{title}</h2>
          <p class="ps-item__summary">{summary}</p>
        </div>
      </a>
    </li>"""


def page_head(title, desc, css):
    return HEAD_TPL.format(
        title=html_lib.escape(title), desc=html_lib.escape(desc), css=css
    )


def topbar_html(prefix, current):
    """文章页共用的主导航。prefix：文章页为 '../'；current：home/works/articles。
    文章页都在 articles/ 下，所以「文章」指向同目录的 index.html。"""
    def mark(key):
        return ' aria-current="page"' if key == current else ""
    return TOPBAR_TPL.format(
        brand=html_lib.escape(SITE_BRAND),
        home=prefix + "index.html",
        about=prefix + "about.html",
        works=prefix + "works.html",
        articles="index.html",
        cur_home=mark("home"),
        cur_works=mark("works"),
        cur_articles=mark("articles"),
    )


def page_foot(js):
    return FOOT_TPL.format(js=js)


# ============================================================
# 5. 主流程
# ============================================================

def make_slug(front, title):
    custom = front.get("slug")
    if isinstance(custom, str) and custom.strip():
        return re.sub(r"[^a-z0-9-]", "", custom.strip().lower()) or "post"
    digest = hashlib.md5(title.encode("utf-8")).hexdigest()[:8]
    return "a-" + digest


def format_date(front, md_path, body=""):
    """日期优先级：frontmatter 的 created/date → 正文里的「原文日期：…」 → 文件修改时间。"""
    raw = front.get("created") or front.get("date") or ""
    if isinstance(raw, list):
        raw = raw[0] if raw else ""
    found = match_date(str(raw))
    if found:
        return found
    snippet = body[:1200]
    m = re.search(r"原文日期[:：]\s*(\d{4})\s*年\s*(\d{1,2})\s*月\s*(\d{1,2})\s*日", snippet)
    if not m:
        m = re.search(r"(?<!\d)(\d{4})\s*年\s*(\d{1,2})\s*月\s*(\d{1,2})\s*日", snippet)
    if m:
        return "%04d-%02d-%02d" % (int(m.group(1)), int(m.group(2)), int(m.group(3)))
    stamp = os.path.getmtime(md_path)
    return datetime.datetime.fromtimestamp(stamp).strftime("%Y-%m-%d")


def match_date(text):
    m = re.match(r"(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})", text)
    if m:
        return "%04d-%02d-%02d" % (int(m.group(1)), int(m.group(2)), int(m.group(3)))
    return None


def collect(keywords):
    """扫描源目录，返回符合条件文章的原始信息列表。"""
    src_dir = os.path.join(VAULT_ARTICLES_DIR, SOURCE_SUBDIR)
    if not os.path.isdir(src_dir):
        print("× 找不到文章源目录：%s" % src_dir)
        sys.exit(1)

    found, skipped = [], []
    for root, dirs, files in os.walk(src_dir):
        dirs[:] = [d for d in dirs if d not in ("attachments", ".obsidian", ".trash")]
        for name in sorted(files):
            if not name.lower().endswith(".md"):
                continue
            if keywords and not any(k in name for k in keywords):
                continue
            path = os.path.join(root, name)
            front, body = split_frontmatter(read_text(path))
            status = front.get("status") or ""
            if isinstance(status, list):
                status = status[0] if status else ""
            if status != WANT_STATUS and front.get("web") not in ("true", True):
                skipped.append((name, status or "无 status"))
                continue
            title = front.get("title") if isinstance(front.get("title"), str) else None
            title = (title or first_heading(body) or os.path.splitext(name)[0]).strip()
            found.append({
                "path": path,
                "front": front,
                "body": body,
                "title": title,
                "date": format_date(front, path, body),
                "slug": make_slug(front, title),
            })
    # 同名文章（标题相同）会算出相同 slug，按文件路径再补一小段哈希区分，避免互相覆盖
    seen = set()
    for doc in found:
        slug = doc["slug"]
        if slug in seen:
            slug = "%s-%s" % (slug, hashlib.md5(doc["path"].encode("utf-8")).hexdigest()[:4])
            n = 2
            while slug in seen:
                slug = "%s-%d" % (doc["slug"], n)
                n += 1
        doc["slug"] = slug
        seen.add(slug)
    return found, skipped


def sync_one(doc):
    art_dir = os.path.join(ARTICLES_DIR)
    if not os.path.isdir(art_dir):
        os.makedirs(art_dir)

    summary = doc["front"].get("summary")
    if isinstance(summary, list):
        summary = ""
    body_html, first_img, paras = convert_body(
        doc["body"], os.path.dirname(doc["path"]), doc["slug"], doc["title"]
    )
    if not (isinstance(summary, str) and summary.strip()):
        longer = [p for p in paras if len(p) >= 24]
        summary = (longer or paras or [""])[0]
    summary = re.sub(r"\s+", " ", summary).strip()
    if len(summary) > 64:
        summary = summary[:64] + "…"

    cover = doc["front"].get("cover")
    if not (isinstance(cover, str) and cover.strip()):
        cover = first_img or ""

    html = (
        page_head(
            "%s ｜ %s" % (doc["title"], SITE_NAME),
            summary or SITE_TAGLINE,
            "../assets/css/site.css",
        )
        + topbar_html("../", "articles")
        + ARTICLE_TPL.format(
            title=html_lib.escape(doc["title"]),
            date=doc["date"],
            body=body_html,
        )
        + page_foot("../assets/js/site.js")
        + "\n" + GENERATED_MARK + "\n"
    )
    out_path = os.path.join(ARTICLES_DIR, doc["slug"] + ".html")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)

    doc["summary"] = summary
    doc["cover"] = cover
    return doc


def write_list_page(items):
    rows = []
    for it in items:
        thumb_html = ""
        if it["cover"]:
            thumb_html = (
                '<div class="ps-item__thumb"><img src="%s" alt="" loading="lazy"></div>'
                % html_lib.escape(it["cover"], quote=True)
            )
        rows.append(LIST_ITEM_TPL.format(
            url=it["slug"] + ".html",
            thumb=thumb_html,
            date=it["date"],
            title=html_lib.escape(it["title"]),
            summary=html_lib.escape(it["summary"]),
        ))
    html = (
        page_head("文章 ｜ %s" % SITE_NAME, "我写过的文章。", "../assets/css/site.css")
        + topbar_html("../", "articles")
        + LIST_TPL.format(
            count=len(items),
            items="\n".join(rows) if rows else '    <li class="ps-item"><p class="ps-item__summary">还没有同步文章。</p></li>',
        )
        + page_foot("../assets/js/site.js")
        + "\n" + GENERATED_MARK + "\n"
    )
    with open(os.path.join(ARTICLES_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(html)


def write_data_js(items):
    lines = ["/* 由 tools/sync_articles.py 自动生成，请勿手改 */", "window.PS_ARTICLES = ["]
    for it in items:
        lines.append("  {")
        lines.append('    title: %s,' % js_str(it["title"]))
        lines.append('    date: %s,' % js_str(it["date"]))
        lines.append('    summary: %s,' % js_str(it["summary"]))
        lines.append('    url: %s,' % js_str("articles/" + it["slug"] + ".html"))
        lines.append('    cover: %s' % js_str(it["cover"]))
        lines.append("  },")
    lines.append("];")
    with open(DATA_JS, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def js_str(value):
    return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")


def cleanup_orphans(slugs):
    """删掉以前生成、现在已不在清单里的文章页。"""
    if not os.path.isdir(ARTICLES_DIR):
        return
    for name in os.listdir(ARTICLES_DIR):
        if not name.endswith(".html") or name == "index.html":
            continue
        path = os.path.join(ARTICLES_DIR, name)
        if name[:-5] in slugs:
            continue
        try:
            with open(path, "r", encoding="utf-8") as f:
                if GENERATED_MARK in f.read(4000):
                    os.remove(path)
                    print("  – 移除过期文章页 %s" % name)
        except OSError:
            pass


def main():
    keywords = [a for a in sys.argv[1:] if not a.startswith("-")]
    partial = bool(keywords)

    print("读取文章源：%s/%s" % (VAULT_ARTICLES_DIR, SOURCE_SUBDIR))
    docs, skipped = collect(keywords)
    if not docs:
        print("× 没有找到符合条件（status: %s）的文章。" % WANT_STATUS)
    else:
        docs.sort(key=lambda d: (d["date"], d["title"]), reverse=True)
        for doc in docs:
            sync_one(doc)
            print("  ✓ %s  →  articles/%s.html" % (doc["title"], doc["slug"]))

    write_list_page(docs)
    write_data_js(docs)
    print("  ✓ 生成列表页 web/articles/index.html")
    print("  ✓ 生成数据文件 web/assets/js/articles-data.js")

    if not partial:
        cleanup_orphans(set(d["slug"] for d in docs))
    else:
        print("（试水模式：只处理上面这些文章，没有清理其它旧页面）")

    if skipped:
        print("\n跳过的 %d 篇（status 不是「已发布」）：" % len(skipped))
        for name, status in skipped[:12]:
            print("  · %s（%s）" % (name, status))
        if len(skipped) > 12:
            print("  · …还有 %d 篇" % (len(skipped) - 12))

    if WARNINGS:
        print("\n提醒：")
        for w in WARNINGS:
            print("  ! %s" % w)

    print("\n完成。")


if __name__ == "__main__":
    main()
